version: "3.9"

services:
  db:
    image: postgres:15
    container_name: buildmas_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: buildmas
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: buildmas_backend
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/buildmas
    command: npm run dev

volumes:
  db_data:
